import {
	EXERCISES_PHRASES_TYPE,
	EXERCISES_TERMS_TYPE,
	MATERIALS_SYNTHETIC_TYPE,
} from '../const';

export type ONLY_EXERCISES_TYPES =
	| typeof EXERCISES_PHRASES_TYPE
	| typeof EXERCISES_TERMS_TYPE;
export type ALL_EXERCISES_TYPES =
	| typeof EXERCISES_PHRASES_TYPE
	| typeof EXERCISES_TERMS_TYPE
	| typeof MATERIALS_SYNTHETIC_TYPE;
